// Used to add data in redis  if not exist in redis
export const dashboardFields = [
  "totalAdmins",
  "totalUsers",
  "totalMen",
  "totalWomen",
  "totalPersonalAccounts",
  "totalBusinessAccounts",
  "newUsersToday",
  "activeUsers",
  "inactiveUsers",
  "totalVisitors",

  "totalLoginInDay",
  "totalRevenue",
  "monthlyRevenue",
  "totalProfit",
  "averageOrderValue",

  "totalCategories",
  "totalSubcategories",
  "totalBrands",
  "totalTypes",
  "mostVisitedCategory",
  "totalVisitedCategory",

  "totalReports",
  "newReportsToday",
  "pending",
  "reviewed",
  "resolved",
  "totalReportConversations",
  "totalReportItems",
  "totalDeleteReports",

  "totalItems",
  "totalDeleteItems",
  "totalDeleteOrders",
  "newItemsToday",
  "underReview",
  "approved",
  "published",
  "sold",
  "reject",

  "totalOrders",
  "newOrdersToday",
  "pending",
  "delivered",
  "canceled",
  "refund",
  "processing",
  "shipped",

  "totalSellers",
  "newSellersThisMonth",
  "topSellingSellers",
  "bestSellingProduct",

  "totalReviews",
  "positiveReviews",
  "negativeReviews",
  "averageRating",
  "totalBad",
  "totalAverage",
  "totalGood",
  "totalVeryGood",
  "totalExcellent",
  "newReviewsToday",

  "totalRegisterWithPhone",
  "totalRegisterWithEmail",
  "totalSuccessLogins",
  "totalFailedLogins",
  "total2FASuccess",
  "total2FAFailed",
  "totalUpdatePassword",
  "totalResetPassword",
  "totalDeletedAccounts",
  "totalBlockedAccounts",
  "totalUnauthorizedAPIRequests",
  "totalAccessDenied",
];

// Used to get data from redis and add in database by using loop in very item in array like this  =>> [users.totalAdmins]
export const dashboardSections = {
  users: [
    "totalAdmins",
    "totalUsers",
    "totalMen",
    "totalWomen",
    "totalPersonalAccounts",
    "totalBusinessAccounts",
    "newUsersToday",
    "activeUsers",
    "inactiveUsers",
    "totalVisitors",
    "totalLoginInDay",
  ],
  financial: [
    "totalRevenue",
    "monthlyRevenue",
    "totalProfit",
    "averageOrderValue",
  ],
  categories: [
    "totalCategories",
    "totalSubcategories",
    "totalBrands",
    "totalTypes",
    "mostVisitedCategory",
    "totalVisitedCategory",
  ],
  reports: [
    "totalReports",
    "newReportsToday",
    "pending",
    "reviewed",
    "resolved",
    "totalReportConversations",
    "totalReportItems",
    "totalDeleteReports",
  ],
  items: [
    "totalItems",
    "totalDeleteItems",
    "newItemsToday",
    "underReview",
    "approved",
    "published",
    "sold",
    "reject",
  ],
  orders: [  
    "totalOrders",
    "newOrdersToday",
    "pending",
    "delivered",
    "canceled",
    "refund",
    "processing",
    "shipped",
    "totalDeleteOrders",
  ],
  sellersBuyersActivity: [
    "totalSellers",
    "newSellersThisMonth",
    "topSellingSellers",
    "bestSellingProduct",
  ],
  reviews: [
    "totalReviews",
    "positiveReviews",
    "negativeReviews",
    "averageRating",
    "totalBad",
    "totalAverage",
    "totalGood",
    "totalVeryGood",
    "totalExcellent",
    "newReviewsToday",
  ],
  security: [
    "totalRegisterWithPhone",
    "totalRegisterWithEmail",
    "totalSuccessLogins",
    "totalFailedLogins",
    "total2FASuccess",
    "total2FAFailed",
    "totalUpdatePassword",
    "totalResetPassword",
    "totalDeletedAccounts",
    "totalBlockedAccounts",
    "totalUnauthorizedAPIRequests",
    "totalAccessDenied",
  ],
};
